name: Go Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.4
      - name: Install Make
        run: |
          sudo apt update
          sudo apt install -y make
         
      - name: Build
        run: make build

  test:
    name: Test
    needs: ["build"]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.4

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test -v ./...
      
      - name: Deploy to AWS EC2
        uses: actions/ssh-action@master
        with:
          host: ${{secrets.EC2_PUBLIC_IP}}
          username: ubuntu
          key: ${{secrets.EC2_SSH_KEY}}
          script: |
            echo "Connected to AWS EC2 instance"
            cd anyfashion/ecommerce-gin-clean-code/
            git pull
            make build
            sudo systemctl restart mygoapp.service
